# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 17283);
user_pref("datareporting.sessions.current.main", 1372);
user_pref("datareporting.sessions.current.startTime", "1515604713872");
user_pref("datareporting.sessions.current.totalTime", 23);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1515579257136,\"a\":2,\"t\":43,\"c\":true,\"m\":1369,\"fp\":30449,\"sr\":-1}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"45.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1485374628000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485374674000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485375443000}}}");
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "002bb7c9-85db-4579-a730-0a9f535508e");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("toolkit.telemetry.cachedClientID", "389fc466-4c58-4da9-9594-ea0e8c54807d");
user_pref("toolkit.telemetry.previousBuildID", "20170125182329");
